create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  available_date date not null,
  available_time text not null,
  status text not null default 'available' check (status in ('available','reserved')),
  created_at timestamptz not null default now(),
  unique (available_date, available_time)
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.availability(id) on delete restrict,
  reserved_date date not null,
  reserved_time text not null,
  status text not null default 'confirmed',
  created_at timestamptz not null default now(),
  unique (slot_id)
);

alter table public.availability enable row level security;
alter table public.reservations enable row level security;

drop policy if exists "Public can view available slots" on public.availability;
create policy "Public can view available slots" on public.availability for select to anon using (status = 'available');

-- Reservations and availability writes are performed by secure server routes using the service role.
-- Never expose SUPABASE_SERVICE_ROLE_KEY to the browser.

insert into public.availability (available_date, available_time)
values
  ('2026-08-22','7:00 PM'),
  ('2026-08-22','8:30 PM'),
  ('2026-08-23','6:30 PM'),
  ('2026-08-29','7:00 PM')
on conflict (available_date, available_time) do nothing;
